In [1]:
import os
import numpy as np
from os.path import join

In [2]:
# preliminary data Exploration 
hair_colours = ['black', 'blond', 'brown', 'gray']
dataset_directory = 'C:\\Users\\suhas\\Documents\\study\\ML Practice\\image_dataset'  ## CHANGE TO YOUR OWN DIRECTORY

images_train = np.load(join(dataset_directory, 'train_images.npy'))
labels_train = np.load(join(dataset_directory, 'train_labels.npy'))

image_size = 48
images_train_rs = images_train.reshape([-1, image_size, image_size, 3]) / 255.0
print("After reshaping image train shape is:",images_train_rs.shape)
print("After reshaping image train data is:",images_train_rs[0])

After reshaping image train shape is: (98479, 48, 48, 3)
After reshaping image train data is: [[[0.99215686 0.90588235 0.76078431]
  [0.99215686 0.90588235 0.76078431]
  [0.99215686 0.90588235 0.76078431]
  ...
  [0.54901961 0.37254902 0.27843137]
  [0.87843137 0.79607843 0.59607843]
  [1.         0.94117647 0.89411765]]

 [[0.99215686 0.90588235 0.76078431]
  [0.99215686 0.90588235 0.76078431]
  [0.99215686 0.90588235 0.76078431]
  ...
  [0.64705882 0.48627451 0.34901961]
  [0.93333333 0.86666667 0.7254902 ]
  [0.99607843 0.94117647 0.89019608]]

 [[0.99215686 0.90588235 0.76078431]
  [0.99215686 0.90588235 0.76078431]
  [0.99215686 0.90588235 0.76078431]
  ...
  [0.75686275 0.61568627 0.41176471]
  [0.97647059 0.91764706 0.85098039]
  [0.98039216 0.94117647 0.8745098 ]]

 ...

 [[0.82352941 0.54117647 0.38039216]
  [0.76862745 0.50588235 0.3372549 ]
  [0.4745098  0.23921569 0.12156863]
  ...
  [0.57254902 0.37647059 0.31764706]
  [0.6        0.39607843 0.34901961]
  [0.63529412 0.427

In [3]:
Features = images_train_rs.shape[1]*images_train_rs.shape[2]*images_train_rs.shape[3]
Features

6912

In [4]:
lst1 = [None] * images_train_rs.shape[0]
for i in range(images_train_rs.shape[0]):
    lst1[i] = images_train_rs[i].reshape([-1])
#print(lst)
x = np.array(lst1).reshape(images_train_rs.shape[0],Features)
print(x.shape)

(98479, 6912)


In [5]:
images_val = np.load(join(dataset_directory, 'val_images.npy'))
labels_val = np.load(join(dataset_directory, 'val_labels.npy'))
files_val = np.load(join(dataset_directory, 'val_files.npy'))

In [6]:
images_val_rs = images_val.reshape([-1, image_size, image_size, 3]) / 255.0

In [7]:
Features1 = images_val_rs.shape[1]*images_val_rs.shape[2]*images_val_rs.shape[3]
Features1

6912

In [8]:
lst3 = [None] * images_val_rs.shape[0]
for i in range(images_val_rs.shape[0]):
    lst3[i] = images_val_rs[i].reshape([-1])
#print(lst)
y = np.array(lst3).reshape(images_val_rs.shape[0],Features1)
print(y.shape)

(12270, 6912)


In [9]:
import time
t1 = time.time()
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score
model = GaussianNB()
model = model.fit(x, labels_train)
val_pred = model.predict(y)
print("Accuracy score for validation is:",accuracy_score(labels_val, val_pred))
t2 = time.time()
print(t2-t1)

Accuracy score for validation is: 0.5748981255093725
48.02410554885864
